version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    # env_file:
    #     - ./.env
    environment:
      - POSTGRES_SERVER=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_DB=db
      - POSTGRES_USER=burak
      - ALGORITHM=HS256
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_DB=db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: