version: "3"
services:
  api:
    image: burakblm/core4all:latest  # Updated to use the Docker Hub image instead of building locally
    ports:
      - 8000:8000
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_DB=db
      - POSTGRES_USER=burak
      - ALGORITHM=HS256
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_USER=burak
      - POSTGRES_DB=db
    volumes:
      - postgres-db:/var/lib/postgresql/data

  prestart:
    image: burakblm/core4all:latest  # Use the same image to run prestart script
    command: bash /app/scripts/prestart.sh
    environment:
      - PYTHONPATH=/app
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=Burak115
      - POSTGRES_DB=db
      - POSTGRES_USER=burak
      - ALGORITHM=HS256
    depends_on:
      - postgres
      - api

volumes:
  postgres-db:
