"""user edited

Revision ID: caa6e3e0d5d2
Revises: 83c6cf7b2d7f
Create Date: 2024-11-10 16:10:24.740107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa6e3e0d5d2'
down_revision: Union[str, None] = '83c6cf7b2d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
