name: SSH into GCP VM and Run Python Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v4

        - name: Install python version 3.12
          uses: actions/setup-python@v5
          with:
            python-version: '3.12' 

        - name: update pip
          run: python -m pip install --upgrade pip

        - name: install all dependencies
          run: pip install -r requirements.txt

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/core4all:latest


  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.GCP_VM_HOST }} >> ~/.ssh/known_hosts


    - name: Run main.py on GCP VM
      env:
        HOST: ${{ secrets.GCP_VM_HOST }}
        USER: ${{ secrets.GCP_VM_USERNAME }}
      run: |
        ssh $USER@$HOST << "EOF"
        sudo docker pull burakblm/core4all:latest

        container_id=$(sudo docker ps -aqf "ancestor=burakblm/core4all")
        if [ -n "$container_id" ]; then
        sudo docker stop "$container_id"
        sudo docker rm "$container_id"
        fi

        sudo docker run -d -p 8000:8000 burakblm/core4all:latest
        EOF